name: Gyankosh

on:
  push:
    branches: [ master ]
jobs:
  laravel-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: NPM Install
      run: npm install
    - name: NPM Production
      run: npm run production
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd /var/www/html/gyankosh/
          git checkout -f 
          git pull



