name: Gyankosh

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-16.04
    steps:
      - name: Php Version
        with:
          php-version: 7.4
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Javascript Compile
        run: |
          npm install
          npm run prod

